# This is a basic workflow to help you get started with Actions

name: Deploy

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install & build
        run:
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: pps-frontend
          path: .

  deploy:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: build
      

      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: pps-frontend